const suites=[{name:"סוויטה 1 — The Engine Room",reason:"כי חברות שזזות מהר צריכות מרחב שמתאים לקצב — עם גישה מיידית לכל מה שצריך.",tags:["אנרגיה גבוהה","גמישות מלאה","עיצוב open"],highlights:['80 מ"ר',"עד 20 אנשים","גישה מהירה לכניסה"],icons:["📐","👥","⚡"]},{name:"סוויטה 3 — The Corner",reason:"שני חלונות, שני כיוונים — בדיוק כמו חברה שיודעת לחשוב בכמה כיוונים בו זמנית.",tags:["אור טבעי","שני חלונות","פינתית"],highlights:['110 מ"ר',"עד 25 אנשים","פינתית עם נוף כפול"],icons:["📐","👥","🏙️"]},{name:"סוויטה 5 — The Kitchen Club",reason:"הרעיונות הכי טובים קורים ליד המטבח. הסוויטה הזו שם בדיוק.",tags:["ליד המטבח","חיי צוות","אינפורמלי ומקצועי"],highlights:['95 מ"ר',"עד 22 אנשים","שני צעדים מהקפה"],icons:["📐","👥","☕"]},{name:"סוויטה 7 — The Skyline",reason:"כי חברה כמו שלכם צריכה לראות רחוק — לא רק לחשוב רחוק.",tags:["נוף פנורמי","קומה גבוהה","פרמיום"],highlights:['140 מ"ר',"עד 32 אנשים","נוף פנורמי לתל אביב"],icons:["📐","👥","🌇"]},{name:"סוויטה 9 — The Quiet Floor",reason:"כשצריך לחשוב בשקט — באמת בשקט — זו הסוויטה שנבנתה בשבילכם.",tags:["שקט מוחלט","פוקוס","מבודד"],highlights:['120 מ"ר',"עד 28 אנשים","הכי שקטה בבניין"],icons:["📐","👥","🎧"]},{name:"סוויטה 11 — The Flagship",reason:"הגדולה ביותר. הפרמיום ביותר. לחברות שלא מתפשרות — על כלום.",tags:["הכי גדולה","חדרי ישיבות פנימיים","פרסטיז'"],highlights:['220 מ"ר',"עד 60 אנשים","חדרי ישיבות פנימיים"],icons:["📐","👥","🏆"]}];
const answers={};let currentQ=0;const totalQ=5;
function pickSuite(a){if(a[2]==="view")return suites[3];if(a[1]==="xlarge"||a[4]==="expand")return suites[5];if(a[1]==="large"&&a[3]==="meetings")return suites[5];if(a[1]==="large")return suites[3];if(a[2]==="food")return suites[2];if(a[2]==="quiet"||a[3]==="focus")return suites[4];if(a[0]==="crypto"||a[0]==="tech")return suites[0];if(a[0]==="enterprise"||a[0]==="consulting")return suites[3];if(a[1]==="medium")return suites[1];return suites[1]}
function showSection(id){["hero","quizSection","resultSection","contactSection"].forEach(s=>{const el=document.getElementById(s);if(!el)return;if(s==="quizSection"){el.classList.toggle("active",s===id);el.classList.toggle("hidden",s!==id)}else{el.classList.toggle("hidden",s!==id)}});window.scrollTo({top:0,behavior:"smooth"})}
function updateProgress(){document.getElementById("progressFill").style.width=((currentQ+1)/totalQ*100)+"%";document.getElementById("questionCount").textContent=`${currentQ+1} / ${totalQ}`}
function goToQuestion(i){document.querySelectorAll(".question").forEach((q,j)=>{q.classList.remove("active","entering");if(j===i)q.classList.add("active","entering")});currentQ=i;updateProgress()}
function showResult(){const s=pickSuite(answers);document.getElementById("resultSuiteName").textContent=s.name;document.getElementById("resultReason").textContent=s.reason;document.getElementById("resultTags").innerHTML=s.tags.map(t=>`<span class="tag">${t}</span>`).join("");document.querySelectorAll(".highlight-text").forEach((el,i)=>{if(s.highlights[i])el.textContent=s.highlights[i]});document.querySelectorAll(".highlight-icon").forEach((el,i)=>{if(s.icons[i])el.textContent=s.icons[i]});showSection("resultSection")}
document.addEventListener("DOMContentLoaded",()=>{
document.getElementById("startBtn").addEventListener("click",()=>{showSection("quizSection");updateProgress()});
document.querySelectorAll(".option").forEach(btn=>{btn.addEventListener("click",()=>{btn.closest(".question").querySelectorAll(".option").forEach(o=>o.classList.remove("selected"));btn.classList.add("selected");answers[currentQ]=btn.dataset.value;setTimeout(()=>{if(currentQ<totalQ-1)goToQuestion(currentQ+1);else showResult()},260)})});
document.getElementById("showFormBtn").addEventListener("click",()=>showSection("contactSection"));
document.getElementById("retakeBtn").addEventListener("click",()=>{Object.keys(answers).forEach(k=>delete answers[k]);document.querySelectorAll(".option").forEach(o=>o.classList.remove("selected"));currentQ=0;goToQuestion(0);showSection("quizSection")});
document.getElementById("contactForm").addEventListener("submit",e=>{e.preventDefault();document.getElementById("contactForm").classList.add("hidden");document.getElementById("formSuccess").classList.remove("hidden")})});
